### ISSUE TITLE
ruff --fix not removing unused imports

### ISSUE THREAD

**Issue by lek18** [charliermarsh/ruff-pre-commit#122]
Hi Ruff Team,

I am noticing the following behavior with ruff --fix on unused imports:

This does NOT work
```
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      exclude: '^resources|config'
    - id: ruff
      args: [ "check", "--select", "I", "--fix" ]
      exclude: '^resources|config'
    # Run the formatter.
    - id: ruff-format
      exclude: '^resources|config'
```
This DOES work:
```
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ "--fix" , "."]
      exclude: '^resources|config'
    - id: ruff
      args: [ "check", "--select", "I", "--fix" ]
      exclude: '^resources|config'
    # Run the formatter.
    - id: ruff-format
      exclude: '^resources|config'
```

Difference = args: [ "--fix" , "."] vs NOT args: [ --fix ]. Should the docs show to use "."? or it should automatically use the current dir?

Edit : I saw this on the docs (default should be .):
```
ruff check --fix --help
Run Ruff on the given files or directories

Usage: ruff check [OPTIONS] [FILES]...

Arguments:
  [FILES]...  List of files or directories to check [default: .]

```

Also I have tried this with ( types_or: [ python, pyi ]):
```
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.5
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
....
```

sample.py
```python
import pandas as pd ## unused.


def myfunct():
    pass
```
