### ISSUE TITLE
Could you tag latest version also with `latest` so we get automatic updates?

### ISSUE THREAD

**Issue by Ambro17** [charliermarsh/ruff-pre-commit#16]
Currently, the docs suggest you to specify the rev in your precommit file
```
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.209'
  hooks:
    - id: ruff
      args: ["--force-exclude"]
```
My request would be to also be able to do
```diff
repo: https://github.com/charliermarsh/ruff-pre-commit
-   rev: 'v0.0.209'
+   rev: 'latest'
     hooks:
         - id: ruff
           args: ["--force-exclude"]
```
to always run the latest release.

Perhaps it's currently possible, but i didn't find it on the docs

Thank you for your awesome work! I have refactored our whole codebase with it in a few PRs, autofix is :rocket:
