### ISSUE TITLE
Question: Proper way of excluding some rules 

### ISSUE THREAD

**Issue by senovr** [charliermarsh/ruff-pre-commit#27]
Hi, 
I am trying to disable line-lengths check in pre-commit with ruff.
I tried 

```
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.245'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix,--ignore 'E501']
```

but it produces an error:
```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 2

error: unexpected argument '--ignore E501' found

  note: argument '--ignore' exists

```
I tried E501 both with and without extra quotes, result is the same.
I also tried '--line-length 100' - result is the same.

Can you please advise what is the proper way to include extra params in ruff pre-commit?
