### ISSUE TITLE
How to use flake8-print in pre-commit-config.yaml?

### ISSUE THREAD

**Issue by barisortac** [charliermarsh/ruff-pre-commit#36]
`flake8-print` seems to have no effect when I try to use it (ruff works perfectly). My configuration is:

```
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.261
  hooks:
    - id: ruff
      args: [--fix]
      additional_dependencies: [flake8-print]
```

How can I make it work? Additionality, if I change the `additional_dependencies: [flake8-print]` to something else -> `additional_dependencies: [flake5-print]`, it gives an error `ERROR: No matching distribution found for flake5-print` therefore I understand that it installs but not using it.

 I also cannot see `flake8-print` if I run `ruff config`.

**Comment by charliermarsh** [comment]
So, unlike with Flake8, all of the extra "plugins" that Ruff supports are built into Ruff directly, and you can turn them on and off by selecting the relevant rule codes.

For example:

```yaml
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.261
  hooks:
    - id: ruff
      args: [--fix, --select, T20]  # https://beta.ruff.rs/docs/rules/#flake8-print-t20
```
